#!/usr/bin/env python3
"""
spec.py — the third task type, and the one that tests whether any of this
generalises past screenshots.

**The task.** Given a source passage and a claim about it, say whether the claim
is fully supported by the source. That is the check every distillation pipeline
in this vault needs and does not have: the funnel reads an article and writes a
note, and the failure that matters is a note asserting something the article
never said.

**The method is unchanged, which is the point.** The vision set plants a defect
in a working screen. This plants a falsehood in a passage taken verbatim from a
real document. Both give ground truth without a labeller, and both are scored on
the same two axes:

    catch rate        does it notice the planted falsehood
    false-alarm rate  does it call a faithful passage unfaithful

If the same two numbers describe quality for a text task and a vision task, the
measuring kit is not vision tooling — it is a way of defining quality, and the
task type is a parameter.

**Why the faithful version is verbatim rather than a written summary.** A summary
generated by a model would need checking by a human before it could be called
faithful, which is the labelling cost this whole approach exists to avoid. An
extract is faithful by construction. The task being measured — is this claim
supported by that text — is the same either way.

Each corruption is mechanical, so it is exact. Nothing here is a judgement call.
"""
import re

# Each entry: how to break one true statement, and the shape of what it breaks.
# `find` locates something corruptible; `apply` returns the corrupted text, or
# None when the passage has nothing of that kind — in which case that class
# simply does not apply, exactly like a mutation whose group is absent.
CORRUPTIONS = [
    {
        "id": "number-swap",
        "what": "a figure is changed to a different figure",
        "why_it_matters": "the commonest distillation error, and the least visible",
        "pattern": re.compile(r"\b(\d[\d,]{0,8}(?:\.\d+)?)\b"),
        "change": lambda m: _bump(m.group(1)),
    },
    {
        "id": "negation",
        "what": "a statement is reversed by inserting or removing 'not'",
        "why_it_matters": "flips the meaning while leaving every keyword intact",
        # Only auxiliaries where a bare "not" is grammatical. "has not a
        # destination" is ungrammatical, and an ungrammatical claim tests
        # grammar rather than faithfulness — it would inflate every catch rate.
        "pattern": re.compile(r"\b(is|are|was|were|can|will|should|must)\b"),
        "change": lambda m: f"{m.group(1)} not",
    },
    {
        "id": "quantifier-flip",
        "what": "'every' becomes 'some', 'never' becomes 'always'",
        "why_it_matters": "turns a rule into a tendency, or a tendency into a rule",
        "pattern": re.compile(r"\b(every|all|never|always|none|any|no)\b", re.I),
        "change": lambda m: {"every": "some", "all": "some", "never": "always",
                             "always": "never", "none": "most", "any": "every",
                             "no": "every"}[m.group(1).lower()],
    },
    {
        "id": "unit-swap",
        "what": "a unit of time or size is changed",
        "why_it_matters": "a plausible sentence that is off by orders of magnitude",
        "pattern": re.compile(r"\b(days?|weeks?|months?|hours?|minutes?|KB|MB|GB)\b"),
        "change": lambda m: {"day": "week", "days": "weeks", "week": "month",
                             "weeks": "months", "month": "day", "months": "days",
                             "hour": "minute", "hours": "minutes",
                             "minute": "hour", "minutes": "hours",
                             "KB": "GB", "MB": "KB", "GB": "MB"}[m.group(1)],
    },
    {
        "id": "comparison-invert",
        "what": "'more' becomes 'less', 'before' becomes 'after'",
        "why_it_matters": "reverses a direction while reading perfectly naturally",
        "pattern": re.compile(r"\b(more|less|fewer|greater|higher|lower|before|after|"
                              r"cheaper|dearer|faster|slower)\b", re.I),
        "change": lambda m: {"more": "less", "less": "more", "fewer": "more",
                             "greater": "smaller", "higher": "lower",
                             "lower": "higher", "before": "after", "after": "before",
                             "cheaper": "dearer", "dearer": "cheaper",
                             "faster": "slower", "slower": "faster"}[m.group(1).lower()],
    },
    {
        "id": "entity-swap",
        "what": "a named thing is replaced with a named thing from elsewhere",
        "why_it_matters": "attributes a real fact to the wrong subject",
        # A capitalised word at the start of a sentence is usually an ordinary
        # word, not a name. Swapping "After" for "Vercel" breaks the grammar
        # instead of the fact, so sentence-initial tokens and common words are
        # excluded and the match must look like an actual identifier.
        "pattern": re.compile(r"(?<![.!?]\s)(?<!^)\b([A-Z][a-zA-Z0-9_.\-]{3,}"
                              r"(?:\.[a-z]{2,4})?)\b"),
        "change": None,          # needs a name from a different document
    },
]

QUESTION = ("Read the source, then the claim.\n\n"
            "SOURCE:\n{source}\n\n"
            "CLAIM:\n{claim}\n\n"
            "Is every statement in the claim fully supported by the source? "
            "Answer with exactly one word: TRUE or FALSE.")


# Capitalised words that are ordinary English, not names. Swapping one of these
# produces nonsense rather than a false claim.
NOT_NAMES = {
    "after", "before", "every", "their", "there", "these", "those", "which",
    "while", "where", "what", "when", "that", "this", "then", "than", "with",
    "without", "because", "since", "until", "unless", "though", "although",
    "however", "instead", "rather", "still", "also", "both", "each", "many",
    "most", "some", "such", "same", "only", "just", "even", "once", "twice",
    "another", "anything", "everything", "nothing", "someone", "everyone",
    "nobody", "here", "from", "into", "over", "under", "about", "above",
    "below", "between", "during", "against", "among", "through", "being",
    "having", "doing", "using", "given", "taken", "written", "read", "run",
    "runs", "running", "does", "done", "will", "would", "could", "should",
    "must", "shall", "might", "they", "them", "your", "yours", "ours",
    "theirs", "itself", "himself", "herself", "themselves", "nowhere",
}


def _bump(num):
    """Change a figure to a clearly different one, keeping its shape so the
    sentence still reads naturally."""
    clean = num.replace(",", "")
    try:
        v = float(clean)
    except ValueError:
        return None
    new = int(v * 3) + 7 if v else 42
    if "." in clean:
        return f"{v * 3 + 7:.1f}"
    return f"{new:,}" if "," in num else str(new)
